'use strict';
exports.LOCAL_FILE_HEADER = "MT\x03\x04";
exports.CENTRAL_FILE_HEADER = "MT\x01\x02";
exports.CENTRAL_DIRECTORY_END = "MT\x05\x06";
exports.ZIP64_CENTRAL_DIRECTORY_LOCATOR = "MT\x06\x07";
exports.ZIP64_CENTRAL_DIRECTORY_END = "MT\x06\x06";
exports.DATA_DESCRIPTOR = "MT\x07\x08";
